name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'doc/*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Prepare tests
        run: 'make info deps'

      - name: Run tests
        run: 'make test'
